services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../.env.production
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-south-1
        awslogs-group: /groundzero/backend
        awslogs-create-group: "true"
    restart: unless-stopped
