"""add_board_to_students

Revision ID: 11cd30f9d335
Revises: e96d77d20e83
Create Date: 2026-03-01 12:17:42.993412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11cd30f9d335'
down_revision: Union[str, None] = 'e96d77d20e83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('board', sa.String(length=20), server_default='cbse', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'board')
    # ### end Alembic commands ###
