"""add_batch_student_enrollments

Revision ID: 42ca15fc726f
Revises: 7195e8ef67a4
Create Date: 2026-03-05 15:40:02.632352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42ca15fc726f'
down_revision: Union[str, None] = '7195e8ef67a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_student_enrollments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['live_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'batch_id', name='uq_student_batch')
    )
    op.create_index(op.f('ix_batch_student_enrollments_batch_id'), 'batch_student_enrollments', ['batch_id'], unique=False)
    op.create_index(op.f('ix_batch_student_enrollments_student_id'), 'batch_student_enrollments', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_batch_student_enrollments_student_id'), table_name='batch_student_enrollments')
    op.drop_index(op.f('ix_batch_student_enrollments_batch_id'), table_name='batch_student_enrollments')
    op.drop_table('batch_student_enrollments')
    # ### end Alembic commands ###
