"""add conversation jsonb to bm_sessions

Revision ID: 4eb817bcc3c4
Revises: 5d0c144872f0
Create Date: 2026-03-08 12:15:27.647072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4eb817bcc3c4'
down_revision: Union[str, None] = '5d0c144872f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bm_sessions', sa.Column('conversation', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bm_sessions', 'conversation')
    # ### end Alembic commands ###
