"""add image_url to bm_questions

Revision ID: 550ca812e8bf
Revises: b6d9bd5af1b6
Create Date: 2026-03-09 22:39:30.774914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '550ca812e8bf'
down_revision: Union[str, None] = 'b6d9bd5af1b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bm_questions', sa.Column('image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bm_questions', 'image_url')
    # ### end Alembic commands ###
