"""add_bm_questions_table_and_question_id_to_turns

Revision ID: 5d0c144872f0
Revises: 7f81964cbe90
Create Date: 2026-03-07 00:05:13.175348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d0c144872f0'
down_revision: Union[str, None] = '7f81964cbe90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bm_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grade_band', sa.String(length=10), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('curriculum_anchor', sa.String(length=300), nullable=True),
    sa.Column('pillars', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('strong_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('watchout_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grade_band', 'question_number', name='uq_bm_questions_grade_number')
    )
    op.create_index('ix_bm_questions_grade_band', 'bm_questions', ['grade_band'], unique=False)
    op.add_column('bm_turns', sa.Column('question_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'bm_turns', 'bm_questions', ['question_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bm_turns', type_='foreignkey')
    op.drop_column('bm_turns', 'question_id')
    op.drop_index('ix_bm_questions_grade_band', table_name='bm_questions')
    op.drop_table('bm_questions')
    # ### end Alembic commands ###
