"""add_plain_password_to_users

Revision ID: 7195e8ef67a4
Revises: 54f94734c82e
Create Date: 2026-03-05 15:18:22.468484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7195e8ef67a4'
down_revision: Union[str, None] = '54f94734c82e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('plain_password', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'plain_password')
    # ### end Alembic commands ###
