"""initial_schema

Revision ID: a0b9987dd356
Revises: 
Create Date: 2026-02-28 20:17:41.428797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0b9987dd356'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('module_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('session_number', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('grade_bands', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('learning_outcomes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('primary_competencies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('secondary_competencies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prerequisites', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cohorts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('grade_band', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pillars',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('grade_band', sa.String(length=5), nullable=False),
    sa.Column('cohort_id', sa.UUID(), nullable=True),
    sa.Column('diagnostic_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('diagnostic_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capabilities',
    sa.Column('id', sa.String(length=1), nullable=False),
    sa.Column('pillar_id', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pillar_id'], ['pillars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cohort_id', sa.UUID(), nullable=True),
    sa.Column('activity_id', sa.String(length=100), nullable=True),
    sa.Column('facilitator_name', sa.String(length=200), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competencies',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('capability_id', sa.String(length=1), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('assessment_method', sa.String(length=20), nullable=False),
    sa.Column('default_params', postgresql.JSONB(astext_type=sa.Text()), server_default='{"pL0": 0.10, "pT": 0.15, "pG": 0.25, "pS": 0.10}', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facilitator_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('engagement', sa.Integer(), nullable=False),
    sa.Column('notable_moment', sa.Text(), nullable=True),
    sa.Column('intervention_flag', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('codevelopment_edges',
    sa.Column('source_id', sa.String(length=10), nullable=False),
    sa.Column('target_id', sa.String(length=10), nullable=False),
    sa.Column('transfer_weight', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['competencies.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['competencies.id'], ),
    sa.PrimaryKeyConstraint('source_id', 'target_id')
    )
    op.create_table('evidence_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('competency_id', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('module_id', sa.String(length=50), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('outcome', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_propagated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('source_event_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_events_competency_id'), 'evidence_events', ['competency_id'], unique=False)
    op.create_index(op.f('ix_evidence_events_student_id'), 'evidence_events', ['student_id'], unique=False)
    op.create_index('ix_evidence_student_competency_time', 'evidence_events', ['student_id', 'competency_id', 'created_at'], unique=False)
    op.create_table('prerequisite_edges',
    sa.Column('source_id', sa.String(length=10), nullable=False),
    sa.Column('target_id', sa.String(length=10), nullable=False),
    sa.Column('min_stage', sa.Integer(), server_default='2', nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['competencies.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['competencies.id'], ),
    sa.PrimaryKeyConstraint('source_id', 'target_id')
    )
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.String(length=50), nullable=False),
    sa.Column('competency_id', sa.String(length=10), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correct_answer', sa.String(length=200), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('grade_band', sa.String(length=5), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_competency_id'), 'questions', ['competency_id'], unique=False)
    op.create_table('student_competency_states',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('competency_id', sa.String(length=10), nullable=False),
    sa.Column('p_learned', sa.Float(), server_default='0.10', nullable=False),
    sa.Column('p_transit', sa.Float(), server_default='0.15', nullable=False),
    sa.Column('p_guess', sa.Float(), server_default='0.25', nullable=False),
    sa.Column('p_slip', sa.Float(), server_default='0.10', nullable=False),
    sa.Column('total_evidence', sa.Integer(), server_default='0', nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_stuck', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_evidence_at', sa.DateTime(), nullable=True),
    sa.Column('stability', sa.Float(), server_default='7.0', nullable=False),
    sa.Column('avg_response_time_ms', sa.Float(), nullable=True),
    sa.Column('stage', sa.Integer(), server_default='1', nullable=False),
    sa.Column('confidence', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'competency_id'),
    sa.UniqueConstraint('student_id', 'competency_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_competency_states')
    op.drop_index(op.f('ix_questions_competency_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_table('prerequisite_edges')
    op.drop_index('ix_evidence_student_competency_time', table_name='evidence_events')
    op.drop_index(op.f('ix_evidence_events_student_id'), table_name='evidence_events')
    op.drop_index(op.f('ix_evidence_events_competency_id'), table_name='evidence_events')
    op.drop_table('evidence_events')
    op.drop_table('codevelopment_edges')
    op.drop_table('facilitator_notes')
    op.drop_table('competencies')
    op.drop_table('sessions')
    op.drop_table('capabilities')
    op.drop_table('students')
    op.drop_table('pillars')
    op.drop_table('cohorts')
    op.drop_table('activities')
    # ### end Alembic commands ###
