"""add_daily_timing_to_live_batch_sessions

Revision ID: a1afee95460c
Revises: 42ca15fc726f
Create Date: 2026-03-05 16:30:37.912339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1afee95460c'
down_revision: Union[str, None] = '42ca15fc726f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live_batch_sessions', sa.Column('daily_timing', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('live_batch_sessions', 'daily_timing')
    # ### end Alembic commands ###
