"""add student_invites table and drop plain_password

Revision ID: adf110d52a50
Revises: 4412709c8461
Create Date: 2026-03-09 23:02:30.602031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'adf110d52a50'
down_revision: Union[str, None] = '4412709c8461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_invites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_invites_token_hash'), 'student_invites', ['token_hash'], unique=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.drop_column('users', 'plain_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('plain_password', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_index(op.f('ix_student_invites_token_hash'), table_name='student_invites')
    op.drop_table('student_invites')
    # ### end Alembic commands ###
