"""add mode column to activities

Revision ID: b32be161b067
Revises: c7f1a3b5d890
Create Date: 2026-03-07 12:48:31.607652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b32be161b067'
down_revision: Union[str, None] = 'c7f1a3b5d890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('mode', sa.String(length=20), server_default='default', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'mode')
    # ### end Alembic commands ###
