"""merge livebatch into cohort add live_rooms

Revision ID: b7fae0043243
Revises: adf110d52a50
Create Date: 2026-03-09 23:35:10.351045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7fae0043243'
down_revision: Union[str, None] = 'adf110d52a50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cohort_enrollments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('cohort_id', sa.UUID(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'cohort_id', name='uq_student_cohort')
    )
    op.create_index(op.f('ix_cohort_enrollments_cohort_id'), 'cohort_enrollments', ['cohort_id'], unique=False)
    op.create_index(op.f('ix_cohort_enrollments_student_id'), 'cohort_enrollments', ['student_id'], unique=False)
    op.create_table('live_rooms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('hms_room_id', sa.String(length=50), nullable=False),
    sa.Column('room_code_host', sa.String(length=20), nullable=True),
    sa.Column('room_code_guest', sa.String(length=20), nullable=True),
    sa.Column('is_live', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.drop_table('live_batch_sessions')
    op.drop_index(op.f('ix_batch_student_enrollments_batch_id'), table_name='batch_student_enrollments')
    op.drop_index(op.f('ix_batch_student_enrollments_student_id'), table_name='batch_student_enrollments')
    op.drop_table('batch_student_enrollments')
    op.drop_table('live_batches')
    op.add_column('cohorts', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('cohorts', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('sessions', sa.Column('title', sa.String(length=300), nullable=True))
    op.add_column('sessions', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('sessions', sa.Column('day', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('order', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('scheduled_at', sa.DateTime(), nullable=True))
    op.add_column('sessions', sa.Column('template_session_id', sa.UUID(), nullable=True))
    op.add_column('sessions', sa.Column('is_locally_modified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('sessions', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('sessions', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'sessions', 'template_sessions', ['template_session_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.alter_column('sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('sessions', 'updated_at')
    op.drop_column('sessions', 'created_at')
    op.drop_column('sessions', 'is_locally_modified')
    op.drop_column('sessions', 'template_session_id')
    op.drop_column('sessions', 'scheduled_at')
    op.drop_column('sessions', 'order')
    op.drop_column('sessions', 'day')
    op.drop_column('sessions', 'description')
    op.drop_column('sessions', 'title')
    op.drop_column('cohorts', 'updated_at')
    op.drop_column('cohorts', 'description')
    op.create_table('batch_student_enrollments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('batch_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('enrolled_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['live_batches.id'], name=op.f('batch_student_enrollments_batch_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('batch_student_enrollments_student_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('batch_student_enrollments_pkey')),
    sa.UniqueConstraint('student_id', 'batch_id', name=op.f('uq_student_batch'))
    )
    op.create_index(op.f('ix_batch_student_enrollments_student_id'), 'batch_student_enrollments', ['student_id'], unique=False)
    op.create_index(op.f('ix_batch_student_enrollments_batch_id'), 'batch_student_enrollments', ['batch_id'], unique=False)
    op.create_table('live_batch_sessions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('batch_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('template_session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('day', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_locally_modified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('daily_timing', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('hms_room_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('hms_room_code_host', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('hms_room_code_guest', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('is_live', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['live_batches.id'], name=op.f('live_batch_sessions_batch_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_session_id'], ['template_sessions.id'], name=op.f('live_batch_sessions_template_session_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('live_batch_sessions_pkey')),
    sa.UniqueConstraint('batch_id', 'template_session_id', name=op.f('uq_batch_template_session'))
    )
    op.create_table('live_batches',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('daily_timing', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('live_batches_pkey'))
    )
    op.drop_table('live_rooms')
    op.drop_index(op.f('ix_cohort_enrollments_student_id'), table_name='cohort_enrollments')
    op.drop_index(op.f('ix_cohort_enrollments_cohort_id'), table_name='cohort_enrollments')
    op.drop_table('cohort_enrollments')
    # ### end Alembic commands ###
