"""add_curriculum_topics

Revision ID: e96d77d20e83
Revises: a0b9987dd356
Create Date: 2026-03-01 11:53:35.340764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e96d77d20e83'
down_revision: Union[str, None] = 'a0b9987dd356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curriculum_topics',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('board', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ncert_ref', sa.String(length=100), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_topics_board'), 'curriculum_topics', ['board'], unique=False)
    op.create_index(op.f('ix_curriculum_topics_grade'), 'curriculum_topics', ['grade'], unique=False)
    op.create_index(op.f('ix_curriculum_topics_subject'), 'curriculum_topics', ['subject'], unique=False)
    op.create_table('topic_competency_map',
    sa.Column('topic_id', sa.String(length=100), nullable=False),
    sa.Column('competency_id', sa.String(length=10), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['curriculum_topics.id'], ),
    sa.PrimaryKeyConstraint('topic_id', 'competency_id')
    )
    op.add_column('questions', sa.Column('topic_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_questions_topic_id'), 'questions', ['topic_id'], unique=False)
    op.create_foreign_key(None, 'questions', 'curriculum_topics', ['topic_id'], ['id'])
    op.create_unique_constraint(None, 'student_competency_states', ['student_id', 'competency_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_competency_states', type_='unique')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_index(op.f('ix_questions_topic_id'), table_name='questions')
    op.drop_column('questions', 'topic_id')
    op.drop_table('topic_competency_map')
    op.drop_index(op.f('ix_curriculum_topics_subject'), table_name='curriculum_topics')
    op.drop_index(op.f('ix_curriculum_topics_grade'), table_name='curriculum_topics')
    op.drop_index(op.f('ix_curriculum_topics_board'), table_name='curriculum_topics')
    op.drop_table('curriculum_topics')
    # ### end Alembic commands ###
